[workspace]
authors = ["Logical Guess"]
channels = ["https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "Butterfly"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = "==0.25.7"
qiskit = ">=2.2.3,<3"
qiskit-aer = ">=0.17.2,<0.18"
